### ISSUE TITLE
CBaseEntity::HasTarget always returns True

### ISSUE THREAD

**Issue by wootguy** [SamVanheer/SC_Angelscript#41]
I was hoping to check if a multi_manager triggers something with this. There's no way to get non-standard keyvalues either.

**Comment by SamVanheer** [comment]
The SDK version overrides the method to check if it has the given target. Unless it was added later and SC never updated it, or removed it, it should work. I checked the Angelscript implementation for that method, and it looks fine.

**Comment by wootguy** [comment]
Oops, yeah it's working. I was using an empty string without knowing.
